## These two functions are used in conjunction with each other to
## simplify matrix inversion computations where needed. 
## The first function caches a list of matrix operations, while the
## second returns the inverse of a matrix (both for a given invertible matrix) 


## The makeCacheMatrix function creates a cached list of matrix operations, 
## specifically, it 
## - sets the value of the matrix
## - gets the value of the matrix
## - sets the inverse of the matrix
## - gets the inverse of the matrix  

makeCacheMatrix <- function(x = matrix()) {
  
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinverse <- function(solve) m <<- solve
  getinverse <- function() m
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)

}


## The cacheSolve function computes for the inverse of a matrix. 
## However, it checks if a cached inverse is available and uses this
## result, thereby saving on redundant computation processes. 
## If no cached inverse exists, it computes the matrix inverse and 
## caches this.
## This function "calls" the lists generated by the makeCacheMatrix()
## function.

cacheSolve <- function(x, ...) {
       
m <- x$getinverse()
  if(!is.null(m)) {                   ##checks if a cached inverse exists
    message("getting cached data")  
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinverse(m)
  m
  ## Return a matrix that is the inverse of 'x'
}
